# --- Build stage -------------------------------------------------------
# Compiles the odasrv (dedicated server) target only. BUILD_CLIENT=0 and
# BUILD_LAUNCHER=0 skip SDL2/SDL2_mixer/wxWidgets entirely — the server
# binary only needs zlib/zstd (system) plus a handful of libs that
# Odamex's CMake pulls in-tree via git submodules (jsoncpp, cpptrace,
# miniupnp, etc). Verified against odamex/odamex CMakeLists.txt.
FROM ubuntu:26.04 AS build

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /build

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends tzdata \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        git \
        gcc g++ \
        cmake \
        make \
        python3 \
        zlib1g-dev \
        libzstd1 libzstd-dev \
        patch \
    && rm -rf /var/lib/apt/lists/*
# NOTE: python3 is REQUIRED, not optional. Odamex generates odamex.wad
# via a Python script (wad/odawad.py) at build time. Without Python,
# CMake silently skips the wad ("Could NOT find Python, ODAMEX.WAD will
# not be built") and the COPY of odamex.wad in the runtime stage fails.

SHELL ["/bin/bash", "-c"]

# Pin the version explicitly — same reproducibility approach as the
# Caddy/xcaddy build. Bump this when you want to pick up a new release.
ARG REPO_URL=https://github.com/odamex/odamex.git
ARG REPO_TAG=12.2.1

RUN git clone --depth 1 --branch "${REPO_TAG}" "${REPO_URL}" odamex

WORKDIR /build/odamex

# Hook for local patches, same pattern used for the NetDuke32 GCC 15
# compatibility fixes. Empty by default — drop .patch files into
# ./patches/ before building if a future toolchain needs a workaround.
COPY patches/ /patches/
RUN shopt -s nullglob \
    && for p in /patches/*.patch; do patch -p1 < "$p"; done

RUN git submodule update --init --depth 1

RUN mkdir build
WORKDIR /build/odamex/build

RUN cmake -W no-dev \
        -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_CXX_COMPILER=g++ \
        -D CMAKE_C_COMPILER=gcc \
        -D BUILD_CLIENT=0 \
        -D BUILD_LAUNCHER=0 \
        -D CMAKE_C_FLAGS="-w" \
        -D CMAKE_CXX_FLAGS="-w" \
        .. \
    && cmake --build . --parallel "$(nproc)" --target odasrv odawad
# IMPORTANT: build BOTH odasrv AND odawad. The wad is produced by a
# separate `odawad` custom target, and odasrv does NOT depend on it
# (the dependency runs the other way: odawad depends on odasrv). So
# `--target odasrv` alone silently skips wad generation entirely — the
# build succeeds but no odamex.wad is ever created, and the runtime
# COPY then fails. Upstream's own Dockerfile has this same latent bug;
# it only builds `--target odasrv`. Building odawad pulls in odasrv as
# a dependency and also copies the wad next to the binary in server/.

# --- Runtime stage -------------------------------------------------------
FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive
ENV INSTALL_DIR=/usr/local/games/odamex

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends tini \
    && rm -rf /var/lib/apt/lists/*

# We run the server as the base image's built-in 'ubuntu' user (UID 1000,
# GID 1000), selected via the compose `user:` directive. No root, no
# runtime user creation, no gosu privilege drop — the container never
# runs as root at any point. This assumes the host user is also UID 1000
# (true across this homelab); if it isn't, set `user:` in compose/.env to
# the correct value. Make sure ubuntu's home exists and is owned by it,
# since odasrv writes state under ~/.odamex.
RUN mkdir -p /home/ubuntu/.odamex \
    && chown -R ubuntu:ubuntu /home/ubuntu

RUN mkdir -p "${INSTALL_DIR}"
COPY --from=build /build/odamex/build/server/odasrv ${INSTALL_DIR}/
# odamex.wad is generated by odawad.py (requires python3 + building the
# odawad target — see notes above). CONFIRMED BY INSPECTING A REAL BUILD:
# the generated wad lands in the wad/ build subdirectory. (The CMake
# recipe also has a step meant to copy it next to the odasrv binary in
# server/, but that copy doesn't reliably fire, so we grab it straight
# from its source location in wad/.) NOT optional — a plain COPY fails
# if the source is missing.
COPY --from=build /build/odamex/build/wad/odamex.wad ${INSTALL_DIR}/odamex.wad

COPY odamex-server.sh /usr/local/bin/odamex-server
RUN chmod +x /usr/local/bin/odamex-server

# HOME must be set explicitly: Docker does NOT populate HOME from
# /etc/passwd when a container runs under the `user:` directive, so
# without this odasrv wouldn't know where ~/.odamex is.
ENV HOME=/home/ubuntu

# tini stays as PID 1 for signal forwarding + zombie reaping (it runs
# fine as the non-root ubuntu user). The privilege-drop entrypoint script
# is gone — there's nothing to drop from, since compose starts us as
# ubuntu directly. `-host` is baked in here; the wad/config args come
# from the compose `command:`.
ENTRYPOINT ["tini", "--", "/usr/local/bin/odamex-server", "-host"]